version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: inbox_navigator_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inbox_navigator
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: inbox_navigator_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inboxnavigator.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: